#!/bin/bash
#
#	/etc/rc.d/init.d/switchmap
#
# This is a Unix init.d startup file for SwitchMap.
# Author: Josh Malone, jmalone@nrao.edu
#
# chkconfig: 345 99 99
# description: Run the switchmap program
# processname: switchmap-daemon

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

#
# See how we were called.
#

start() {
	# Check if it is already running
	if [ ! -f /var/lock/subsys/switchmap ]; then
	echo -n $"Starting switchmap daemon: "
	/opt/services/switchmap/switchmap-daemon &
	touch /var/lock/subsys/switchmap
	success 'switchmap'
	echo
	fi
	return 0
}

stop() {
	echo -n $"Stopping switchmap daemon: "
	killproc -p /var/run/switchmap.pid
	RETVAL=$?
	[ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/switchmap
	echo
	return $RETVAL
}

restart() {
	stop
	start
}	

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
reload)
	reload
	;;
restart)
	restart
	;;
status)
	status switchmap
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart}"
	exit 1
esac

exit $RETVAL
